[custom.all.cptr]
type = "local"
path = "."
ipkg = "cptr.ipkg"
test = "test/test.ipkg"

[custom.all.cptr-profile]
type = "local"
path = "profile"
ipkg = "profile.ipkg"

[custom.all.struct-gen]
type = "local"
path = "struct-gen"
ipkg = "struct-gen.ipkg"

[custom.all.ref1]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-ref1"
commit = "latest:main"
ipkg   = "ref1.ipkg"
